_target_: src.models.qml_bert_finetune_module.GLUETransformerLitModule
#_target_: src.models.qml_bert_finetune_module_checkmcrp.CheckModule
#src.models.qml_debug.GLUETransformerLitModule
config_path: ${hydra:runtime.cwd}/qbert_config/config.json
checkpoint_path: ${hydra:runtime.cwd}/output/checkpoints-continue-pretrain-5qubit-2-2/last.ckpt
#checkpoint_path: ${hydra:runtime.cwd}/output/checkpoints-continue-pretrain-3qubit-2-2/qbert-epoch=154-global_step=0-train_loss=1.62.ckpt
#num_labels: 2
task_name: mrpc
learning_rate: 5e-5
adam_epsilon: 1e-8
warmup_steps: 0
weight_decay: 0.0
train_batch_size: 32
eval_batch_size: 32
encoder_trainable: false
projection_trainable: true
#eval_splits: ['validation']